Missing Dependency
Hey there just noticed that we are missing the dependency in the docs here for `libpulse-dev` .

Without this compiling of `pocketsphinx` fails with:
```text
deps/sphinxbase/src/libsphinxad/ad_pulse.c:44:30: fatal error: pulse/pulseaudio.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
Not a big contribution but should help new users.

:beers: Cheers! :beers: